sonar.projectKey=zerodowntime-cicd
sonar.projectName=ZeroDowntime-CICD

sonar.host.url=http://localhost:9000


sonar.sources=.

sonar.exclusions=node_modules/**,tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info