apiVersion: v1

kind: Service

metadata:
  name: zerodowntime-service

  namespace: production
spec:
  type: ClusterIP

  selector:
    app: zerodowntime
    version: blue

  ports:

  - protocol: TCP

    port: 80

    targetPort: 3000

  type: NodePort
